export const CLUSTER_URL = "https://cris-dguijg-fast-mainnet.helius-rpc.com";
export const TOKEN_MINT = "E7eq75v6muvR7KSoc3ayWCukBcdDtCauvAq1DWKsqhPV";
export const MIN_JUPITER_ROUTE_REFETCH_INTERVAL = 1000 * 15;
export const FEE_WALLET = "3fWzcS7E6HeZDYTcfWXkmfYtD2q7Ym8pEghFyxz91oKL";
export const FEE_LAMPORTS = 1000000;
export const SOL_LAMORTS_RESERVED = 10000000;
export const TOKEN_DUST_MAX_VALUE = 10;
export const RESERVED_FEE_ACCOUNTS = 1;
export const BLOCKHASH_MAX_AGE_MS = 1000 * 30;
